# https://kubernetes.io/docs/concepts/workloads/pods/

apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  namespace: default
  labels:
    app: server
    instance: server-pod
spec:
  serviceAccountName: pod-creator-sa
  containers:
    - name: server
      image: guillaumemichel1026/rtype-test:latest
      command: [ "sleep" ]
      args: [ "infinity" ]
      ports:
        - containerPort: 4242
          protocol: TCP
        - containerPort: 4243
          protocol: UDP
   #   resources:
   #     requests:
  #        memory: "2Gi"
  #        cpu: "1"
  #        ephemeral-storage: "10Gi"
  #      limits:
  #        memory: "4Gi"
  #        cpu: "2"
  #        requests:
  #        ephemeral-storage: "20Gi"

