apiVersion: v1
kind: Service
metadata:
  name: server-service-tcp
  namespace: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: server
  ports:
    - name: tcp-port
      protocol: TCP
      port: 4242
      targetPort: 4242
