apiVersion: v1
kind: Service
metadata:
  name: server-service-udp
  namespace: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: server
  ports:
    - name: udp-port
      protocol: UDP
      port: 4243
      targetPort: 4243
